version: 1

formatters:
  default:
    format: "[{asctime}] {levelname} {name}: {message}"
    style: "{"
    datefmt: "%D"

handlers:
  std:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    formatter: default
    filename: log_file.txt

loggers:
  root:
    level: INFO
    handlers: [std, file]
    propagate: true